<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Validasi</name>
   <tag></tag>
   <elementGuidId>5e25f8ed-5205-4116-933f-413a032ba78e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[3]/table[2]/tbody/tr/td/div[4]/table/tbody/tr[2]/td[4]/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
